### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by valerio-bozzolan** [Zverik/RevertUI#2]
Hi all :)

Can I help in any way adopting HTTPS in the production instance of this very useful tool?

We usually setup a simple Apache HTTPd webserver as frontend, with simple support to HTTPs with Let's Encrypt, then proxying results to the underlying application who handle plaintext.

Thank you so much for your work!

**Comment by mnalis** [comment]
https://Level0.osmz.ru on same IP already uses Let's encrypt certificates, so I'd guess it should not be too hard to make http://revert.osmz.ru use HTTPS too

**Comment by Zverik** [comment]
Done.
