### ISSUE TITLE
Switch to OAuth 2

### ISSUE THREAD

**Issue by danieldegroot2** [Zverik/RevertUI#4]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

Note, `api.openstreetmap.org` API url currently can not do OAuth 2 handshake. See https://github.com/openstreetmap/operations/issues/951#issuecomment-1748717154
You can split the `www.` base URL and `api.` API url. See https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

cc: @Zverik

**Comment by mnalis** [comment]
I'm wondering if this is easier to do now that https://github.com/Zverik/Level0/issues/71 has implemented Oauth2 successfully, or if the Oauth2 code is not reusable?

**Comment by Zverik** [comment]
I was like, whaaat, this is a python script, I thought I made those with oauth2. And then I saw I wrote this eight years ago, when osm.org did not support OAuth2.

Okay, I'll see to upgrading this then.

**Comment by Zverik** [comment]
Done.
